#!/bin/sh
kubectl run mysql-client --image=mysql:5.7 -i --rm --restart=Never --\
  mysql -h mysql-0.mysql <<EOF
CREATE DATABASE wordpress;
EOF
kubectl autoscale statefulset mysql --cpu-percent=30 --min=1 --max=6
